logging:
  pattern:
    dateformat: "yyyy-MM-dd HH:mm:ss"

spring:
  output:
    ansi:
      enabled: always
  datasource:
    driver-class-name: org.h2.Driver

rsa:
  public-key: classpath:certs/public.pem
  private-key: classpath:certs/private.pem

seed:
  admin:
    email: hexlet@example.com
    password: ${SEED_ADMIN_PASSWORD:qwerty}
