logging:
  level:
    root: WARN
    org:
      springframework:
        security: WARN

spring:
  output:
    ansi:
      enabled: always
  datasource:
    driver-class-name: org.h2.Driver

rsa:
  public-key: classpath:certs/public.pem
  private-key: classpath:certs/private.pem
